# Generated by Django 4.0.2 on 2022-06-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_curso_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='students.student'),
        ),
    ]
